# Generated by Django 5.0.1 on 2024-01-19 23:30

import django.db.models.deletion
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('descripcion', models.TextField(max_length=500)),
                ('img', models.ImageField(blank=True, null=True, upload_to=store.models.get_file_path)),
                ('precio', models.FloatField()),
                ('tendencia', models.BooleanField(default=False, help_text='0=default, 1=Trending')),
                ('tag', models.CharField(max_length=150)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('coleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.coleccion')),
            ],
        ),
    ]
