# Generated by Django 5.0.1 on 2024-01-19 23:37

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='img',
            new_name='img_caja',
        ),
        migrations.AddField(
            model_name='producto',
            name='img_figura',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.get_file_path),
        ),
    ]
