# Generated by Django 5.0.1 on 2024-01-21 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_img_producto_img_caja_producto_img_figura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='img_caja',
            new_name='img',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='img_figura',
        ),
    ]
