# Generated by Django 5.0.1 on 2024-01-23 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_carrito_de_compras_lista_de_deseos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito_de_compras',
            old_name='product',
            new_name='productos',
        ),
    ]
