# Generated by Django 5.0.1 on 2024-01-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_productos_carrito_de_compras_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lista_de_deseos',
            old_name='product',
            new_name='producto',
        ),
        migrations.AddField(
            model_name='lista_de_deseos',
            name='creado',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
