# Generated by Django 5.0.1 on 2024-01-23 22:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_lista_de_deseos_creado'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista_de_deseos',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
