# Generated by Django 5.0.1 on 2024-01-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_lista_de_deseos_creado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista_de_deseos',
            name='creado',
            field=models.DateTimeField(default='2024012319:54:50'),
        ),
    ]
