# Generated by Django 5.0.1 on 2024-02-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='estrellas',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=1),
        ),
    ]
